_prefs: 
  baselayer: ''
  print: true
  saveCenter: false
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 0
  - 20
  - 2
description: ''
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: null
maxzoom: 21
minzoom: 0
name: Mapbox Outdoors
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
styles: 
  - style.mss
  - road.mss
  - label.mss
  - poi.mss
template: ''
